#Jekyll settings
encoding: UTF-8
permalink:	pretty
highlighter: rouge
include: ['.gitignore']
sass:
  style: compressed

title: JUSTAOS
email: support@justaos.com
description: Sleek and powerful platform for faster and easier application development
tagline: Sleek and powerful platform for faster and easier application development

# Author details
author:
  name:           'Shivaji Varma'
  location:        'Bangalore, India'
  gpage:          +ShivajivarmaDotCom
  email:          contact@shivajivarma.com
  avatar:         /profile.min.png
  github:         justaos
  linkedin:       justaos
  twitter:        just_a_os

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://justaos.com

script: 'https://cdn.jsdelivr.net/npm/@goatui/components@1.3.0/dist/goatui/goatui.esm.js'
themeCss: 'https://cdn.jsdelivr.net/npm/@goatui/components@1.3.0/dist/goatui/assets/styles/theme.css'

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ''

# Path to assets
css:      /assets/css
img:      /assets/img
js:       /assets/js
fonts:    /assets/fonts
docs:     /assets/docs


compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-assets


assets:

  assets:
    - "*.png"

  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets

defaults:
  -
    scope:
      path: "assets/material-kit/**/*.*"
    values:
      sitemap:         false
  -
    scope:
      path: "assets/includes/**/*.*"
    values:
      sitemap:         false


# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-assets
  - jekyll-spark
  - jekyll-redirect-from
